#' Update water quality  data in database
#'
#' Inserts and updates water quality data in the database. Performs
#' an update on records that already exist in the database but
#' have a different result value. Inserts any new records that do
#' not already exist in the database.
#'
#' @param con database connection object
#' @param df data frame containing water quality records to insert/update.
#'   Typically generated by \code{dbhydro_clean_wq(...)} or \code{dbhydro_get_wq(..., raw = FALSE)}.
#'
#' @return TRUE if operation was successful
#' @export
#'
#' @importFrom rlang .data
#' @examples
#' \dontrun{
#' df <- dbhydro_get_wq(
#'   station_ids = c("LOX3", "LOX6"),
#'   date_min = "2019-01-01",
#'   date_max = "2019-11-30"
#' )
#' db_update_dbhydro_wq(con, df)
#' }
db_update_dbhydro_wq <- function (con, df) {
  if (nrow(df) == 0) {
    logger::log_info("no data to update, doing nothing")
    return(TRUE)
  }

  station_ids <- unique(df$station_id)
  logger::log_info("updating {nrow(df)} wq records ({length(station_ids)} unique stations)")

  # fetch existing dbkeys
  db_stations <- db_get_dbhydro_stations(con, station_ids = station_ids)

  missing_stations <- setdiff(station_ids, db_stations$station_id)

  if (length(missing_stations) > 0) {
    logger::log_error("{length(missing_stations)} stations are missing in the database, please add them and then try again ({paste0(missing_stations, collapse = ', ')})")
    return(FALSE)
  }

  # fetch existing data from db
  date_min <- min(df$date)
  date_max <- max(df$date)
  df_existing <- DBI::dbGetQuery(
    con,
    glue::glue_sql(
      "SELECT id, station_id, wq_param, sample_id, project_code, quality_code, value as db_value FROM dbhydro_wq WHERE station_id IN ({station_ids*}) AND date >= {date_min} AND date <= {date_max}",
      .con = con
    )
  )

  # generate insert/update dataframes
  if (nrow(df_existing) == 0) {
    logger::log_debug("no existing wq data in database, inserting all records")
    df_insert <- df
    df_update <- data.frame()
  } else {
    df_merge <- df |>
      dplyr::left_join(df_existing, by = c("station_id", "wq_param", "sample_id", "project_code", "quality_code"))

    df_insert <- df_merge |>
      dplyr::filter(is.na(.data$id)) |>
      dplyr::select(-c("id", "db_value"))

    df_update <- df_merge |>
      dplyr::filter(!is.na(.data$id), abs(.data$value - .data$db_value) > 0.0001) |>
      dplyr::select(-c("db_value"))
  }

  # update existing (delete then insert)
  if (nrow(df_update) == 0) {
    logger::log_info("no existing records need to be updated")
  } else {
    logger::log_info("updating {nrow(df_update)} existing record(s) of {nrow(df)} total")
    logger::log_debug("deleting {nrow(df_update)} record(s)")
    n_deleted <- DBI::dbExecute(con, glue::glue_sql("DELETE FROM dbhydro_wq WHERE id IN ({ids*})", ids = df_update$id, .con = con))

    if (n_deleted != nrow(df_update)) {
      logger::log_error("failed to delete {nrow(df_update)} record(s), only {n_deleted} succeeded")
      return(FALSE)
    }

    logger::log_debug("inserting {nrow(df_update)} record(s) that were deleted")
    # df_update <- df_update |>
    #   dplyr::mutate_at(c("first_trigger_date", "collection_date", "measure_date", "receive_date", "filtration_date"), format, format = "%Y-%m-%d %H:%M:%S%z") |>
    #   str
    ok <- DBI::dbWriteTable(con, "dbhydro_wq", df_update, append = TRUE, row.names = FALSE)

    if (!ok) {
      logger::log_error("failed to insert {nrow(df_update)} during update portion of upsert")
      return(FALSE)
    }
  }

  # insert (new records)
  if (nrow(df_insert) == 0) {
    logger::log_info("no new records to insert")
  } else {
    logger::log_info("inserting {nrow(df_insert)} new record(s)")
    ok <- DBI::dbWriteTable(con, "dbhydro_wq", df_insert, append = TRUE, row.names = FALSE)
    if (!ok) {
      logger::log_error("failed to insert {nrow(df_insert)} new record(s) during insert portion of upsert")
    }
  }

  TRUE
}
