#' Update hydrologic data in database
#'
#' Inserts and updates hydrologic data in the database. Performs
#' an update on records that already exist in the database but
#' have a outdated revision date. Inserts any new records that do
#' not already exist in the database.
#'
#' @param con database connection object
#' @param df data frame containing hydrologic records to insert/update.
#'   Typically generated by \code{dbhydro_clean_hydro(...)} or \code{dbhydro_get_hydro(..., raw = FALSE)}.
#'
#' @return TRUE if operation was successful
#' @export
#'
#' @importFrom rlang .data
#' @examples
#' \dontrun{
#' df <- dbhydro_get_hydro(
#'   dbkeys = c("91473", "91599"),
#'   date_min = "2019-10-01",
#'   date_max = "2019-11-30"
#' )
#' db_update_dbhydro_hydro(con, df)
#' }
db_update_dbhydro_hydro <- function (con, df) {
  if (nrow(df) == 0) {
    logger::log_info("no data to update, doing nothing")
    return(TRUE)
  }
  if (any(is.na(df$dbkey))) {
    logger::log_error("argument df cannot contain NAs in dbkey column")
    return(FALSE)
  }
  if (any(is.na(df$date))) {
    logger::log_error("argument df cannot contain NAs in date column")
    return(FALSE)
  }

  dbkeys <- unique(df$dbkey)
  logger::log_info("updating {nrow(df)} hydrologic records ({length(dbkeys)} unique dbkeys)")

  # fetch existing dbkeys
  db_dbkeys <- db_get_dbhydro_dbkeys(con, dbkeys = dbkeys)

  missing_dbkeys <- setdiff(dbkeys, db_dbkeys$dbkey)

  if (length(missing_dbkeys) > 0) {
    logger::log_error("{length(missing_dbkeys)} dbkeys are missing in the database, please add them and then try again ({paste0(missing_dbkeys, collapse = ', ')})")
    return(FALSE)
  }

  # fetch existing data from db
  date_min <- min(df$date)
  date_max <- max(df$date)
  df_existing <- DBI::dbGetQuery(
    con,
    glue::glue_sql(
      "SELECT id, dbkey, date, revision_date as db_revision_date FROM dbhydro_hydro WHERE dbkey IN ({dbkeys*}) AND date >= {date_min} AND date <= {date_max}",
      .con = con
    )
  )

  # generate insert/update dataframes
  if (nrow(df_existing) == 0) {
    logger::log_debug("no existing hydro data in database, inserting all records")
    df_insert <- df
    df_update <- data.frame()
  } else {
    df_merge <- df %>%
      dplyr::left_join(df_existing, by = c("dbkey", "date"))

    df_insert <- df_merge %>%
      dplyr::filter(is.na(.data$id)) %>%
      dplyr::select(-c("id", "db_revision_date"))

    df_update <- df_merge %>%
      dplyr::filter(!is.na(.data$id), .data$revision_date > .data$db_revision_date) %>%
      dplyr::select(-c("db_revision_date"))
  }

  # update existing (delete then insert)
  if (nrow(df_update) == 0) {
    logger::log_info("no existing records need to be updated")
  } else {
    logger::log_info("updating {nrow(df_update)} existing record(s) of {nrow(df)} total")
    logger::log_debug("deleting {nrow(df_update)} record(s)")
    n_deleted <- DBI::dbExecute(con, glue::glue_sql("DELETE FROM dbhydro_hydro WHERE id IN ({ids*})", ids = df_update$id, .con = con))

    if (n_deleted != nrow(df_update)) {
      logger::log_error("failed to delete {nrow(df_update)} record(s), only {n_deleted} succeeded")
      return(FALSE)
    }

    logger::log_debug("inserting {nrow(df_update)} record(s) that were deleted")
    ok <- DBI::dbWriteTable(con, "dbhydro_hydro", df_update, append = TRUE, row.names = FALSE)

    if (!ok) {
      logger::log_error("failed to insert {nrow(df_update)} during update portion of upsert")
      return(FALSE)
    }
  }

  # insert (new records)
  if (nrow(df_insert) == 0) {
    logger::log_info("no new records to insert")
  } else {
    logger::log_info("inserting {nrow(df_insert)} new record(s)")
    ok <- DBI::dbWriteTable(con, "dbhydro_hydro", df_insert, append = TRUE, row.names = FALSE)
    if (!ok) {
      logger::log_error("failed to insert {nrow(df_insert)} new record(s) during insert portion of upsert")
    }
  }

  TRUE
}
