#' Update USGS daily values data in database
#'
#' Inserts and updates USGS dv data in the database. Performs
#' an update on records that already exist in the database but
#' have a outdated revision date. Inserts any new records that do
#' not already exist in the database.
#'
#' @param con database connection object
#' @param df data frame containing dv records to insert/update.
#'   Typically generated by \code{usgs_clean_dv(...)} or \code{usgs_get_dv(..., raw = FALSE)}.
#'
#' @return TRUE if operation was successful
#' @export
#'
#' @importFrom rlang .data
#' @examples
#' \dontrun{
#' df <- usgs_get_dv(
#'   station_ids = "263180080205001",
#'   param = "stage",
#'   date_min = "2018-01-01",
#'   date_max = "2018-02-01"
#' )
#' db_update_usgs_dv(con, df)
#' }
db_update_usgs_dv <- function (con, df) {
  if (nrow(df) == 0) {
    logger::log_info("no data to update, doing nothing")
    return(TRUE)
  }
  if (any(is.na(df$station_id))) {
    logger::log_error("argument df cannot contain NAs in station_id column")
    return(FALSE)
  }
  if (any(is.na(df$date))) {
    logger::log_error("argument df cannot contain NAs in date column")
    return(FALSE)
  }

  station_ids <- unique(df$station_id)
  logger::log_info("updating {nrow(df)} usgs dv records ({length(station_ids)} stations)")

  # fetch existing stations
  db_stations <- db_get_usgs_stations(con, station_ids = station_ids)

  missing_station_ids <- setdiff(station_ids, db_stations$station_id)

  if (length(missing_station_ids) > 0) {
    logger::log_error("{length(missing_station_ids)} stations are missing in the database, please add them and then try again ({paste0(missing_station_ids, collapse = ', ')})")
    return(FALSE)
  }

  # fetch existing data from db
  date_min <- min(df$date)
  date_max <- max(df$date)
  df_existing <- DBI::dbGetQuery(
    con,
    glue::glue_sql(
      "SELECT id, station_id, param, date, value as db_value FROM usgs_dv WHERE station_id IN ({station_ids*}) AND date >= {date_min} AND date <= {date_max}",
      .con = con
    )
  )

  # generate insert/update dataframes
  if (nrow(df_existing) == 0) {
    logger::log_debug("no existing usgs dv data in database, inserting all records")
    df_insert <- df
    df_update <- data.frame()
  } else {
    df_merge <-

    df_insert <- df %>%
      dplyr::anti_join(df_existing, by = c("station_id", "param", "date"))

    df_update <- df %>%
      dplyr::inner_join(df_existing, by = c("station_id", "param", "date")) %>%
      dplyr::filter(!is.na(.data$id), .data$value != .data$db_value) %>%
      dplyr::select(-.data$db_value)
  }

  # update existing (delete then insert)
  if (nrow(df_update) == 0) {
    logger::log_info("no existing records need to be updated")
  } else {
    logger::log_info("updating {nrow(df_update)} existing record(s) of {nrow(df)} total")
    logger::log_debug("deleting {nrow(df_update)} record(s)")
    n_deleted <- DBI::dbExecute(con, glue::glue_sql("DELETE FROM usgs_dv WHERE id IN ({ids*})", ids = df_update$id, .con = con))

    if (n_deleted != nrow(df_update)) {
      logger::log_error("failed to delete {nrow(df_update)} record(s), only {n_deleted} succeeded")
      return(FALSE)
    }

    logger::log_debug("inserting {nrow(df_update)} record(s) that were deleted")
    ok <- DBI::dbWriteTable(con, "usgs_dv", df_update, append = TRUE, row.names = FALSE)

    if (!ok) {
      logger::log_error("failed to insert {nrow(df_update)} during update portion of upsert")
      return(FALSE)
    }
  }

  # insert (new records)
  if (nrow(df_insert) == 0) {
    logger::log_info("no new records to insert")
  } else {
    logger::log_info("inserting {nrow(df_insert)} new record(s)")
    ok <- DBI::dbWriteTable(con, "usgs_dv", df_insert, append = TRUE, row.names = FALSE)
    if (!ok) {
      logger::log_error("failed to insert {nrow(df_insert)} new record(s) during insert portion of upsert")
    }
  }

  TRUE
}
